package com.owo.dao.mysql;

import com.owo.dao.mysql.entity.Programmer;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProgrammerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    int insert(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    int insertSelective(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    Programmer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Programmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table programmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Programmer record);

    List<Programmer> selectByName(String name);
    List<Programmer> selectAll();

}
